variables:
  Project: hk8591-web
  HtdocsDir: /home/htdocs
  UploadDir: ${HtdocsDir}/hk8591upload
  RuntimeDir: ${HtdocsDir}/hk8591upload/Runtime
  ProjectName: ${Project}-${CI_BUILD_REF_NAME}
  ProjectDir: ${HtdocsDir}/${Project}-${CI_BUILD_REF_NAME}
  ProjectUploadDir: ${HtdocsDir}/www/public/upload
  ProjectRuntimeDir: ${HtdocsDir}/www/app/runtime
  ConfigDir: ${HtdocsDir}/${Project}-${CI_BUILD_REF_NAME}/public/static/js/config
  PHPIMAGE: hub.591.com.tw/php-alpine:5.6.18
  NGINXIMAGE: hub.591.com.tw/tengine:2.1.2
  replicas: "1"
  
stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - sh _gitlabci/build.sh 
  only:
    - /^(master|debug)$/
  tags:
    - addcn
    
job_test:
  stage: test
  script:
    - sh _gitlabci/test.sh
    - mvn sonar:sonar -Dsonar.projectVersion=$CI_BUILD_REF
  only:
    - master
  tags:
    - 28-runner
    
job_deploy:
  stage: deploy
  script:
    - sh _gitlabci/deploy.sh
    - cd /home/htdocs/hk8591;git pull
  only:
    - /^(master|debug)$/
  tags:
    - addcn